site_name: ملزومات لینوکس

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

theme:
  name: material
  custom_dir: docs/overrides
  highlightjs: true
  shortcuts:
    search: 83
  language: fa
  direction: rtl
  feature:
    tabs: false
  palette:
    primary:
    accent:
  font:
    text: "Vazirmatn"
    code: "Roboto Mono"
  icon:
    logo: custom/tux
    favicon: custom/tux
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

plugins:
  - live-edit

nav:
  - "index.md"
  - "contents.md"
  - "preface.md"
  - "help_us.md"
  - "فصل ۱ - انتخاب یک سیستم عامل": "chapters/chapter1/contents.md"
  - "فصل ۲ - درک مجوز نرم افزاری": "chapters/chapter2/contents.md"
  - "فصل ۳ - بررسی اصول و فلسفه لینوکس": "chapters/chapter3/contents.md"
  - "فصل ۴ - استفاده از ابزار های رایج لینوکس": "chapters/chapter4/contents.md"
  - "فصل ۵ - مدیریت سخت افزار": "chapters/chapter5/contents.md"
  - "فصل ۶ - آشنایی با خط فرمان": "chapters/chapter6/contents.md"
  - "فصل ۷ - مدیریت فایل ها": "chapters/chapter7/contents.md"
  - "فصل ۸ - جستجو، استخراج، و آرشیو کردن داده ها": "chapters/chapter8/contents.md"
  - "فصل ۹ - کنکاش پردازش ها و پردازش داده ها": "chapters/chapter9/contents.md"
  - "فصل ۱۰ - ویرایش فایل ها": "chapters/chapter10/contents.md"
  - "فصل ۱۱ - ساخت اسکریپت": "chapters/chapter11/contents.md"
  - "فصل ۱۲ - فهم مقدماتی امنیت": "chapters/chapter12/contents.md"
  - "فصل ۱۳ - ساخت کاربر و گروه": "chapters/chapter13/contents.md"
  - "فصل ۱۴ - تنظیم مالکیت و دسترسی ها": "chapters/chapter14/contents.md"
  - "فصل ۱۵ - مدیریت اتصالات شبکه": "chapters/chapter15/contents.md"
  - "glossary.md"
